//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectMgrEntities : DbContext
    {
        public ProjectMgrEntities()
            : base("name=ProjectMgrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<parentTask> parentTasks { get; set; }
        public virtual DbSet<projectTable> projectTables { get; set; }
        public virtual DbSet<taskTable> taskTables { get; set; }
        public virtual DbSet<usersTable> usersTables { get; set; }
    }
}
