//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersTable
    {
        public int userid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> employeeid { get; set; }
        public Nullable<int> projectid { get; set; }
        public Nullable<int> taskid { get; set; }
    }
}
